=head1 NAME

Mojolicious - PDF::ReportWriter - Example

=head1 DESCRIPTION

This example shows how to create PDF files with L<Mojolicious|http://mojolicio.us>
and L<PDF::ReportWriter>.

Start the script with

  morbo script/mojo_rwr

Navigate to L<http://localhost:3000/> and click on the download link.

=head1 REQUIREMENTS

=over 2

=item Mojolicious

Install as root with:

  curl get.mojolicio.us | sh

=item PDF::ReportWriter

Install from CPAN.

=back

=head1 COPYRIGHT & LICENSE

Copyright 2012 by Tekki.

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.

=cut
